// Predefined feature list, mapped from FlexiBuilder Pro's CLAUDE.md modules.
export const FEATURES = [
  {
    id: "html-converter",
    title: "HTML Converter",
    module: "src/htmlConverter/",
    description: "Перетворює текст/HTML у email-safe HTML і MJML, з готовими шаблонами та експортом.",
    icon: "🧩",
    enabled: true,
  },
  {
    id: "advanced-converter",
    title: "Advanced Converter",
    module: "src/htmlConverter/advanced/",
    description: "DOM-пайплайн для вставки з Google Docs: preprocess → normalize → IR → classify → render.",
    icon: "🛠️",
    enabled: true,
  },
  {
    id: "image-converter",
    title: "Image Converter",
    module: "src/imageConverter/",
    description: "Клієнтська конвертація зображень (JPEG/PNG/WebP/AVIF) на WASM, без сервера.",
    icon: "🖼️",
    enabled: true,
  },
  {
    id: "email-sender",
    title: "Email Sender",
    module: "src/emailSender/",
    description: "Надсилання тестових листів через SMTP (Gmail/Outlook/Yahoo) з формою креденшлів.",
    icon: "✉️",
    enabled: true,
  },
  {
    id: "block-library",
    title: "Block Library",
    module: "src/blockLibrary/",
    description: "Бібліотека email-блоків з категоріями, попереднім переглядом і кастомними блоками.",
    icon: "📚",
    enabled: false,
  },
  {
    id: "template-library",
    title: "Template Library",
    module: "src/templateLibrary/",
    description: "Керування шаблонами листів через файлову систему з пошуком і синхронізацією.",
    icon: "🗂️",
    enabled: true,
  },
  {
    id: "email-validator",
    title: "Email Validator",
    module: "src/emailValidator/",
    description: "Перевірка HTML на сумісність з email-клієнтами: теги, CSS, доступність.",
    icon: "✅",
    enabled: false,
  },
  {
    id: "ai-alt-text",
    title: "AI ALT-текст",
    module: "server/ai/",
    description: "Генерація ALT-тексту і назв зображень через OCR + CLIP + Gemma 3 (локальний Ollama).",
    icon: "🤖",
    enabled: true,
  },
  {
    id: "storage-automation",
    title: "Storage Automation",
    module: "automation/",
    description: "Playwright-автоматизація завантаження файлів у сховища (default/alphaone/ttt).",
    icon: "🚀",
    enabled: true,
  },
  {
    id: "desktop-electron",
    title: "Desktop (Electron)",
    module: "electron/",
    description: "Пакування застосунку в десктопний клієнт для macOS і Windows.",
    icon: "💻",
    enabled: true,
  },
];
